### ISSUE TITLE
Receive problem

### ISSUE THREAD

**Issue by TomNussbaumer** [privatepublic-de/faderfox-editor#1]
While sending works like a charm, whenever I try to receive syx from the EC4 I'll get the following error message:

Received invalid sysex data. Wrong download type.

It's on the latest Chrome (Win10/64) with a brandnew EC4 with the latest firmware installed. Any idea why this is happening?

**Comment by privatepublic-de** [comment]
Please make sure to "send all setups" from your EC4 not only "current setup"!
