### ISSUE TITLE
Implement high-resolution data in Macro mode | EC4

### ISSUE THREAD

**Issue by vigliensoni** [privatepublic-de/faderfox-editor#5]
Hi Peter (@privatepublic-de),

I'm really grateful for all the work and love put into the design of this editor.

I wonder how I should tweak the Faderfox Universal 2 script for Ableton to have high-resolution data being recognized by the DAW in macro mode.

I dug into the `FaderfoxElements` class and saw that the 8 encoders are assigned 7-bit consecutive CC values starting from the `CC_MACRO_BASE_SELECTED_TRACK`. Can these be set up for 14-bit encoding so that Ableton reads high-res data?

Thank you very much in advance.

**Comment by privatepublic-de** [comment]
Hello, I'm sorry but I can't help you with that. I'm not involved in the Ableton Live scripts. Please refer to faderfox directly via info@faderfox.de

Thanks, Peter
